services:
  PrestaShop\Module\PsAccounts\Provider\ModuleDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\ModuleDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\ModuleRepository'

  PrestaShop\Module\PsAccounts\Provider\ProductDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\ProductDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\ProductRepository'
      - '@PrestaShop\Module\PsAccounts\Decorator\ProductDecorator'
      - '@PrestaShop\Module\PsAccounts\Repository\LanguageRepository'
      - '@PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter'

  PrestaShop\Module\PsAccounts\Provider\CategoryDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\CategoryDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\CategoryRepository'
      - '@PrestaShop\Module\PsAccounts\Decorator\CategoryDecorator'
      - '@PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter'

  PrestaShop\Module\PsAccounts\Provider\OrderDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\OrderDataProvider
    arguments:
      - '@ps_accounts.context'
      - '@PrestaShop\Module\PsAccounts\Repository\OrderRepository'
      - '@PrestaShop\Module\PsAccounts\Repository\OrderDetailsRepository'
      - '@PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter'

  PrestaShop\Module\PsAccounts\Provider\CartDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\CartDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\CartRepository'
      - '@PrestaShop\Module\PsAccounts\Repository\CartProductRepository'
      - '@PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter'

  PrestaShop\Module\PsAccounts\Provider\GoogleTaxonomyDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\GoogleTaxonomyDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\GoogleTaxonomyRepository'
      - '@ps_accounts.context'
