services:
  PrestaShop\Module\PsAccounts\Provider\ModuleDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\ModuleDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\ModuleRepository'

  PrestaShop\Module\PsAccounts\Provider\ProductDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\ProductDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\ProductRepository'
      - '@PrestaShop\Module\PsAccounts\Decorator\ProductDecorator'

  PrestaShop\Module\PsAccounts\Provider\CategoryDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\CategoryDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\CategoryRepository'
      - '@PrestaShop\Module\PsAccounts\Decorator\CategoryDecorator'

  PrestaShop\Module\PsAccounts\Provider\OrderDataProvider:
    class: PrestaShop\Module\PsAccounts\Provider\OrderDataProvider
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\OrderRepository'
      - '@ps_accounts.context'
