imports:
  - { resource: ../common.yml }
  - { resource: api.yml }
  - { resource: decorator.yml }
  - { resource: provider.yml }
  - { resource: repository.yml }

services:
  PrestaShop\Module\PsAccounts\Formatter\JsonFormatter:
    class: PrestaShop\Module\PsAccounts\Formatter\JsonFormatter

  PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter:
    class: PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter

  PrestaShop\Module\PsAccounts\Service\CompressionService:
    class: PrestaShop\Module\PsAccounts\Service\CompressionService
    arguments:
      - '@PrestaShop\Module\PsAccounts\Formatter\JsonFormatter'

  PrestaShop\Module\PsAccounts\Service\ProxyService:
    class: PrestaShop\Module\PsAccounts\Service\ProxyService
    arguments:
      - '@PrestaShop\Module\PsAccounts\Api\EventBusProxyClient'
      - '@PrestaShop\Module\PsAccounts\Formatter\JsonFormatter'

  PrestaShop\Module\PsAccounts\Service\ApiAuthorizationService:
    class: PrestaShop\Module\PsAccounts\Service\ApiAuthorizationService
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\AccountsSyncRepository'
      - '@PrestaShop\Module\PsAccounts\Api\EventBusSyncClient'

  PrestaShop\Module\PsAccounts\Service\DeletedObjectsService:
    class: PrestaShop\Module\PsAccounts\Service\DeletedObjectsService
    arguments:
      - '@ps_accounts.context'
      - '@PrestaShop\Module\PsAccounts\Repository\DeletedObjectsRepository'
      - '@PrestaShop\Module\PsAccounts\Service\ProxyService'

  PrestaShop\Module\PsAccounts\Service\SynchronizationService:
    class: PrestaShop\Module\PsAccounts\Service\SynchronizationService
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\AccountsSyncRepository'
      - '@PrestaShop\Module\PsAccounts\Repository\IncrementalSyncRepository'
      - '@PrestaShop\Module\PsAccounts\Service\ProxyService'
