imports:
  - { resource: ../common.yml }
  - { resource: api.yml }
  - { resource: decorator.yml }
  - { resource: provider.yml }
  - { resource: repository.yml }

services:
  PrestaShop\Module\PsAccounts\Formatter\JsonFormatter:
    class: PrestaShop\Module\PsAccounts\Formatter\JsonFormatter

  PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter:
    class: PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter

  PrestaShop\Module\PsAccounts\Service\CompressionService:
    class: PrestaShop\Module\PsAccounts\Service\CompressionService
    arguments:
      - '@PrestaShop\Module\PsAccounts\Formatter\JsonFormatter'

  PrestaShop\Module\PsAccounts\Service\SegmentService:
    class: PrestaShop\Module\PsAccounts\Service\SegmentService
    arguments:
      - '@PrestaShop\Module\PsAccounts\Api\SegmentClient'
      - '@PrestaShop\Module\PsAccounts\Service\CompressionService'

  PrestaShop\Module\PsAccounts\Service\ApiAuthorizationService:
    class: PrestaShop\Module\PsAccounts\Service\ApiAuthorizationService
    arguments:
      [ '@PrestaShop\Module\PsAccounts\Repository\AccountsSyncRepository', '@PrestaShop\Module\PsAccounts\Api\EventBusSyncClient' ]


