project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: '/translations/en.php'
    dest:   '/psaccounts/module.php'
    translation: '/translations/%two_letters_code%.php'
    type: 'php'
    labels:
      - 'psaccounts'
      - 'module'
