---
services:
  config-generator:
    build:
      context: .
      dockerfile: ./config-generator.Dockerfile
    volumes:
      - ./config:/config:rw
    environment:
      ACCOUNT_TAG: ${ACCOUNT_TAG}
      TUNNEL_SECRET: ${TUNNEL_SECRET}
      TUNNEL_ID: ${TUNNEL_ID}
      PS_DOMAIN: ${PS_DOMAIN}
