<?php

namespace PrestaShop\Module\PsAccounts\Tests\Unit\Repository\ConfigurationRespository;

use PrestaShop\Module\PsAccounts\Adapter\Configuration;
use PrestaShop\Module\PsAccounts\Repository\ConfigurationRepository;
use PrestaShop\Module\PsAccounts\Tests\TestCase;

class setShopIdTest extends TestCase
{
    public function setUp()
    {

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @not_a_test
     * FIXME: test with real objects and transaction ?
     */
    public function it_should_pass_shop_id_calling_get()
    {
        $shopId = $this->faker->randomNumber();

        $configMock = $this->getMockBuilder(Configuration::class)
            ->setConstructorArgs([\Context::getContext()])
            ->setMethods(['getRaw'])
            ->getMock();

        $configMock->expects($this->once())
            ->method('getRaw')
            ->with(Configuration::PS_ACCOUNTS_FIREBASE_EMAIL, null, null, $shopId, false);

        $configuration = new ConfigurationRepository($configMock);
        $configuration->setShopId($shopId);

        $configuration->getFirebaseEmail();
    }

    /**
     * @not_a_test
     */
    public function it_should_pass_shop_id_calling_update()
    {
        $shopId = $this->faker->randomNumber();

        $email = $this->faker->safeEmail;
        $configMock = $this->getMockBuilder(Configuration::class)
            ->setConstructorArgs([\Context::getContext()])
            ->setMethods(['setRaw', 'get'])
            ->getMock();

        $configMock->expects($this->once())
            ->method('get')
            ->with(Configuration::PS_PSX_FIREBASE_EMAIL);
        $configMock->expects($this->once())
            ->method('setRaw')
            ->with(Configuration::PS_ACCOUNTS_FIREBASE_EMAIL, $email, false, null, $shopId);

        $configuration = new ConfigurationRepository($configMock);
        $configuration->setShopId($shopId);

        $configuration->updateFirebaseEmail($email);
    }
}
