services:
  PrestaShop\Module\PsAccounts\Account\CommandHandler\DeleteUserShopHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\DeleteUserShopHandler
    public: true
    tags:
      - { name: tactician.handler, command: 'PrestaShop\Module\PsAccounts\Domain\Shop\Command\DeleteUserShopCommand' }
    arguments:
      - '@PrestaShop\Module\PsAccounts\Api\Client\AccountsClient'
      - '@PrestaShop\Module\PsAccounts\Context\ShopContext'
      - '@PrestaShop\Module\PsAccounts\Account\Session\Firebase\ShopSession'
      - '@PrestaShop\Module\PsAccounts\Account\Session\Firebase\OwnerSession'

  PrestaShop\Module\PsAccounts\Account\CommandHandler\UpdateUserShopHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\UpdateUserShopHandler
    public: true
    tags:
      - { name: tactician.handler, command: 'PrestaShop\Module\PsAccounts\Domain\Shop\Command\UpdateShopCommand' }
    arguments:
      - '@PrestaShop\Module\PsAccounts\Api\Client\AccountsClient'
      - '@PrestaShop\Module\PsAccounts\Context\ShopContext'
      - '@PrestaShop\Module\PsAccounts\Account\Session\Firebase\ShopSession'
      - '@PrestaShop\Module\PsAccounts\Account\Session\Firebase\OwnerSession'

  PrestaShop\Module\PsAccounts\Account\CommandHandler\UpgradeModuleHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\UpgradeModuleHandler
    public: true
    arguments:
      - '@PrestaShop\Module\PsAccounts\Api\Client\AccountsClient'
      - '@PrestaShop\Module\PsAccounts\Account\ShopIdentity'
      - '@PrestaShop\Module\PsAccounts\Account\Session\ShopSession'

  PrestaShop\Module\PsAccounts\Account\CommandHandler\UpgradeModulesHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\UpgradeModulesHandler
    public: true
    arguments:
      - '@PrestaShop\Module\PsAccounts\Context\ShopContext'
      - '@PrestaShop\Module\PsAccounts\Cqrs\CommandBus'

  PrestaShop\Module\PsAccounts\Account\CommandHandler\CreateIdentityHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\CreateIdentityHandler
    public: true
    arguments:
      - '@PrestaShop\Module\PsAccounts\Api\Client\AccountsClient'
      - '@PrestaShop\Module\PsAccounts\Provider\ShopProvider'
      - '@PrestaShop\Module\PsAccounts\Identity\Domain\IdentityManager'

  PrestaShop\Module\PsAccounts\Account\CommandHandler\CreateIdentitiesHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\CreateIdentitiesHandler
    public: true
    arguments:
      - '@PrestaShop\Module\PsAccounts\Context\ShopContext'
      - '@PrestaShop\Module\PsAccounts\Cqrs\CommandBus'

  PrestaShop\Module\PsAccounts\Account\CommandHandler\VerifyAuthenticityHandler:
    class: PrestaShop\Module\PsAccounts\Account\CommandHandler\VerifyAuthenticityHandler
    public: true
    arguments:
      - '@PrestaShop\Module\PsAccounts\Api\Client\AccountsClient'
      - '@PrestaShop\Module\PsAccounts\Provider\ShopProvider'
      - '@PrestaShop\Module\PsAccounts\Account\Session\Firebase\ShopSession'
      - '@PrestaShop\Module\PsAccounts\Identity\Domain\IdentityManager'
      - '@PrestaShop\Module\PsAccounts\Account\ManageProof'
