imports:
  - { resource: common/services.yml }

parameters:
  #########################
  # Env overrideable vars

  env(PS_ACCOUNTS_SENTRY_CREDENTIALS): 'https://4c7f6c8dd5aa405b8401a35f5cf26ada@o298402.ingest.sentry.io/5354585'

  #########################
  # Module configuration

  firebase.api_key: 'AIzaSyBEm26bA2KR893rY68enLdVGpqnkoW2Juo'
  firebase.auth_domain: 'prestashop-sso-prod.firebaseapp.com'
  firebase.project_id: 'prestashop-sso-prod'

  sentry.credentials: '%env(string:PS_ACCOUNTS_SENTRY_CREDENTIALS)%'

  accounts.svc_ui_url: 'https://accounts.psessentials.net'
  accounts.svc_api_url: 'https://accounts-api.psessentials.net'

  billing.svc_api_url: 'https://billing-api.psessentials.net'

  sso.resend_verification_email: 'https://auth.prestashop.com/account/send-verification-email'
  sso.manage_account: 'https://auth.prestashop.com/login'

#  à prévoir dans le futur module EventBus
#  SEGMENT_PROXY_API_URL=https://eventbus-proxy.psessentials-integration.net
#  EVENT_BUS_SYNC_API_URL=https://eventbus-sync.psessentials-integration.net
