imports:
  - { resource: common/services.yml }

parameters:
  #########################
  # Env overrideable vars

  env(FIREBASE_API_KEY): 'AIzaSyASHFE2F08ncoOH9NhoCF8_6z7qnoLVKSA'
  env(FIREBASE_AUTH_DOMAIN): 'prestashop-ready-integration.firebaseapp.com'
  env(FIREBASE_PROJECT_ID): 'prestashop-ready-integration'

  env(ACCOUNTS_SVC_UI_URL): 'http://localhost:8080'
  env(ACCOUNTS_SVC_API_URL): 'http://accounts-api'

  env(BILLING_SVC_API_URL): 'https://billing-api.psessentials.net'

  env(SSO_RESEND_VERIFICATION_EMAIL): 'https://auth.prestashop.com/account/send-verification-email'
  env(SSO_MANAGE_ACCOUNT): 'https://eventbus-sync.psessentials-integration.net'

  env(SENTRY_CREDENTIALS): 'https://4c7f6c8dd5aa405b8401a35f5cf26ada@o298402.ingest.sentry.io/5354585'

  #########################
  # Module configuration

  firebase.api_key: '%env(string:FIREBASE_API_KEY)%'
  firebase.auth_domain: '%env(string:FIREBASE_AUTH_DOMAIN)%'
  firebase.project_id: '%env(string:FIREBASE_PROJECT_ID)%'

  accounts.svc_ui_url: '%env(string:ACCOUNTS_SVC_UI_URL)%'
  accounts.svc_api_url: '%env(string:ACCOUNTS_SVC_API_URL)%'

  billing.svc_api_url: '%env(BILLING_SVC_API_URL)%'

  sso.resend_verification_email: '%env(SSO_RESEND_VERIFICATION_EMAIL)%'
  sso.manage_account: '%env(SSO_MANAGE_ACCOUNT)%'

  sentry.credentials: '%env(SENTRY_CREDENTIALS)%'

#  à prévoir dans le futur module EventBus
#  SEGMENT_PROXY_API_URL=https://eventbus-proxy.psessentials-integration.net
#  EVENT_BUS_SYNC_API_URL=https://eventbus-sync.psessentials-integration.net
