ps_accounts_oauth2:
  path: ps_accounts/oauth2
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\PsAccounts\Controller\Admin\OAuth2Controller::initOAuth2Flow'
    _anonymous_controller: true
    _legacy_controller: SfAdminOAuth2PsAccounts
    _legacy_link: SfAdminOAuth2PsAccounts

# TODO: Or we preserve original legacy controller or we create a legacy sf route
#ps_accounts_oauth2_legacy:
#  path: ps_accounts/oauth2_legacy
#  methods: [GET]
#  defaults:
#    _controller: 'PrestaShop\Module\PsAccounts\Controller\Admin\OAuth2Controller::initOAuth2FlowLegacy'
#    _anonymous_controller: true
#    _legacy_controller: AdminOAuth2PsAccounts
#    _legacy_link: AdminOAuth2PsAccounts
