services:
  _defaults:
    public: true

  PrestaShop\Module\PsAccounts\Controller\Admin\LoginController:
    class: PrestaShop\Module\PsAccounts\Controller\Admin\LoginController
    autowire: true
    autoconfigure: true
#    arguments:
#      - '@doctrine.cache.provider'
