<?php

namespace PrestaShop\Module\PsAccounts\Tests\Unit\Service\PsAccountsService;

use PrestaShop\Module\PsAccounts\Service\Accounts\Resource\ShopStatus;
use PrestaShop\Module\PsAccounts\Service\PsAccountsService;
use PrestaShop\Module\PsAccounts\Tests\TestCase;

class IsAccountLinkedTest extends TestCase
{
    /**
     * @inject
     *
     * @var PsAccountsService
     */
    protected $service;

    public function set_up()
    {
        parent::set_up(); // TODO: Change the autogenerated stub

        $this->statusManager->upsetCachedStatus(new ShopStatus([
            'cloudShopId' => $this->faker->uuid,
            'pointOfContactUuid' => $this->faker->uuid,
        ]));
    }

    /**
     * @test
     *
     * @throws \Exception
     */
    public function itShouldReturnTrue()
    {
        $this->assertTrue($this->service->isAccountLinked());
    }

    /**
     * @test
     *
     * @throws \Exception
     */
    public function itShouldReturnFalseWithoutIdentity()
    {
        $this->statusManager->setCloudShopId('');

        $this->assertFalse($this->service->isAccountLinked());
    }

    /**
     * @test
     *
     * @throws \Exception
     */
    public function itShouldReturnFalseWithoutPointOfContact()
    {
        $this->statusManager->upsetCachedStatus(new ShopStatus([
            'pointOfContactUuid' => null,
        ]));

        $this->assertFalse($this->service->isAccountLinked());
    }
}
