services:
  ps_accounts.db:
    class: Db
    factory: [ 'Db', 'getInstance' ]

  ps_accounts.context:
    class: Context
    factory: [ 'Context', 'getContext' ]

  ps_accounts.shop_context:
    class: PrestaShop\Module\PsAccounts\Context\ShopContext

  ps_accounts.link:
    class: Link
    factory: [ 'PrestaShop\Module\PsAccounts\Factory\Link', 'get' ]

  ps_accounts.configuration_adapter:
    class: PrestaShop\Module\PsAccounts\Adapter\Configuration
    arguments:
      - '@ps_accounts.context'

  ps_accounts.link_adapter:
    class: PrestaShop\Module\PsAccounts\Adapter\LinkAdapter
    arguments:
      - '@ps_accounts.link'

  #####################
  # services.yml

  PrestaShop\Module\PsAccounts\Service\PsAccountsService:
    class: PrestaShop\Module\PsAccounts\Service\PsAccountsService
    arguments:
      - '@PrestaShop\Module\PsAccounts\Repository\ConfigurationRepository'
      - '@PrestaShop\Module\PsAccounts\Api\Client\FirebaseClient'
      - '@ps_accounts.context'
      - '@ps_accounts.shop_context'
      - '@ps_accounts.link_adapter'
      - { ui_url: '%accounts.svc_ui_url%', sso_manage_account_url: '%sso.manage_account%' }

  PrestaShop\Module\PsAccounts\Service\PsBillingService:
    class: PrestaShop\Module\PsAccounts\Service\PsBillingService
    arguments:
      - '@PrestaShop\Module\PsAccounts\Api\Client\ServicesBillingClient'
      - '@PrestaShop\Module\PsAccounts\Service\PsAccountsService'
      - '@PrestaShop\Module\PsAccounts\Repository\ConfigurationRepository'
      - '@ps_accounts.context'
      - '@ps_accounts.shop_context'

  #####################
  # handlers.yml

  PrestaShop\Module\PsAccounts\Handler\ErrorHandler\ErrorHandler:
    class: PrestaShop\Module\PsAccounts\Handler\ErrorHandler\ErrorHandler
    arguments:
      - '@PrestaShop\Module\PsAccounts\Service\PsAccountsService'
      - '%sentry.credentials%'

  #####################
  # api.yml

  PrestaShop\Module\PsAccounts\Api\Client\AccountsClient:
    class: PrestaShop\Module\PsAccounts\Api\Client\AccountsClient
    arguments:
      - '@PrestaShop\Module\PsAccounts\Service\PsAccountsService'
      - '@ps_accounts.link'

  PrestaShop\Module\PsAccounts\Api\Client\FirebaseClient:
    class: PrestaShop\Module\PsAccounts\Api\Client\FirebaseClient
    arguments:
      - { api_key: '%firebase.api_key%' }

  PrestaShop\Module\PsAccounts\Api\Client\ServicesBillingClient:
    class: PrestaShop\Module\PsAccounts\Api\Client\ServicesBillingClient
    arguments:
      - '@PrestaShop\Module\PsAccounts\Service\PsAccountsService'
      - '@ps_accounts.link'
      - { api_url: '%billing.svc_api_url%' }

  #####################
  # repository.yml

  PrestaShop\Module\PsAccounts\Repository\ConfigurationRepository:
    class: PrestaShop\Module\PsAccounts\Repository\ConfigurationRepository
    arguments:
      - '@ps_accounts.configuration_adapter'
