#!/bin/bash
openssl genrsa -out private_key.pem 2048
openssl rsa -pubout -in private_key.pem -out public_key.pem

openssl genrsa -out private_key2.pem 2048
openssl rsa -pubout -in private_key2.pem -out public_key2.pem
