name: Module accounts CD

on: [push]
#on:
#  pull_request:
#    types: [opened,edited,reopened,synchronize,labeled]

env:
  MODULE_NAME: ps_accounts
  GCLOUD_TOKEN_PATH: ./token.json

jobs:
  accounts_cd_multi_shop:
    name: Multi shop - Module Accounts continuous deployment
    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    if: contains(github.event.pull_request.labels.*.name, 'quality assurance needed')

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Checkout ps checkout
        uses: actions/checkout@v2
        with:
          repository: PrestaShopCorp/ps_checkout
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ps_checkout

      - run: ls && ls ps_checkout
