on: [push]
#  push:
#    branches:
#      - develop
#      - "*"

jobs:
  accounts_ci:
    name: Module Accounts continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          path: module

#      - name: Install
#        run: |
#          cd module
#          yarn
#          yarn build
#          composer install

      - name: Compress module accounts
        run: |
          tar -czvf accounts.tar.gz module

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

#      - name: Copy key
#        run: |
#          echo $SSH_KEY > key.pub
#          chmod 400 key.pub
#        env:
#          SSH_KEY: ${{ secrets.SSH_KEY }}
#
#      - name: Scp module
#        run: |
#          scp -ikey.pub -oStrictHostKeyChecking=no accounts.tar.gz "$HOST:"
#        env:
#          HOST: ${{ secrets.SSH_HOST }}

#      - name: Test
#        run: |
#          ssh $HOST -ikey.pub  -o StrictHostKeyChecking=no ls -l

