name: Account Module Installation autom tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1-5"

env:
  IMAGE_PREFIX: ghcr.io/prestashopcorp/

jobs:
  run-test:
    name: Run Account tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        shop_version:
          - 1.7.8.7-7.4-fpm-alpine
          - 1.6.1.24-7.1-fpm-alpine
          - 1.7.8.11-7.4-fpm-alpine
          - 1.7.8.8-7.4-fpm-alpine
          - 8.1.0-8.1-fpm-alpine
          - 8.1.1-8.1-fpm-alpine
          - 8.1.5-8.1-fpm-alpine
          - 8.2.0-8.1-fpm-alpine
          - nightly-nginx
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./e2e/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('e2e/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
    
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('e2e/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "node"

      - name: Install dependencies
        working-directory: ./e2e
        run: |
          npm install

      - name: Install playwright browsers
        working-directory: ./e2e
        run: |
          npx playwright install chromium

      - name: Generate .env in e2e file
        working-directory: ./e2e
        run: |
          echo "BASE_URL=${{secrets.BASE_URL}}" >> .env
          echo "BASE_URL_FO=${{secrets.BASE_URL_FO}}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "OAUTH2URL=${{ secrets.OAUTH2URL }}" >> .env
          echo "ACCOUNTSAPIURL=${{ secrets.ACCOUNTSAPIURL }}" >> .env
          echo "ACCOUNTSUIURL=${{ secrets.ACCOUNTSUIURL }}" >> .env
          echo "QA_USER_AGENT=${{ secrets.QA_USER_AGENT}}" >> .env

      - name: Generate .env in e2e-env file
        working-directory: ./e2e-env
        run: |
          echo "ACCOUNT_TAG=${{ secrets.ACCOUNT_TAG }}" >> .env
          echo "TUNNEL_SECRET=${{ secrets.TUNNEL_SECRET }}" >> .env
          echo "TUNNEL_ID=${{ secrets.TUNNEL_ID }}" >> .env
          echo "PS_DOMAIN=${{ secrets.PS_DOMAIN }}" >> .env
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
          echo "DOWNLOADER_TOKEN=${{ secrets.DOWNLOADER_TOKEN }}" >> .env
          echo "PS_VERSION=${{ secrets.PS_VERSION }}" >> .env
          echo "PS_ACCOUNTS_VERSION=${{ secrets.PS_ACCOUNTS_VERSION }}" >> .env

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: prestashopcorp
          password: ${{ secrets.DOWNLOADER_TOKEN }}

      - name: Run test
        working-directory: ./e2e
        run: npm run run-all-tests -- ${{ matrix.shop_version }}
        continue-on-error: true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.shop_version }}
          path: ./e2e/allure-results-${{ matrix.shop_version }}

  merge-allure:
    name: Merge Allure Results, Genreate Roprt & Send Slack notification
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: "actions/checkout@v4"

      - name: Install dependencies
        working-directory: ./e2e
        run: |
          npm install

      - name: Download all allure artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./e2e/

      - name: Merge Allure Results
        working-directory: ./e2e
        run: npm run merge-allure-results

      - name: Generate Allure Report
        working-directory: ./e2e
        run: npm run generate-allure-report
      
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: allure-report
          path: ./e2e/allure-report

      - name: Extract versioned results from Allure suites.json
        id: summary
        working-directory: ./e2e/allure-report/widgets
        run: |
          {
            echo "*Résultats des tests Account AUTOM :* \`${{ github.repository }}\`"
            echo
            jq -r '.items[] | "• \(.name) : ✅ \(.statistic.passed) / ❌ \(.statistic.failed) / ⚠️ \(.statistic.broken)"' suites.json
            echo
            echo "📄 Rapport Allure disponible dans les artifacts du run : 🔗 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Voir le run GitHub Actions>"
            echo
            echo "1️⃣ Téléchargez l'archive du rapport Allure."
            echo "2️⃣ Installez l'outil Allure CLI si ce n'est pas déjà fait!"
            echo "3️⃣ Dans un terminal, placez-vous dans le dossier extrait du rapport, puis exécutez :"
            echo "\`\`\`"
            echo "allure open"
            echo "\`\`\`"
          } > slack_message.txt

      - name: Prepare Slack payload
        run: |
          message=$(cat ./e2e/allure-report/widgets/slack_message.txt | jq -Rs .)
          echo "{\"channel\": \"${{ secrets.SLACK_CHANNEL_ID }}\", \"text\": $message}" > ./e2e/allure-report/widgets/slack_payload.json

      - name: Send Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload-file-path: ./e2e/allure-report/widgets/slack_payload.json

