name: Add a release draft
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Add or update release draft
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/master'
    steps:
      - id: release_info
        uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
