name: DEBUG

on:
  push:
    branches:
      - fix/debug

jobs:
  run:
    name: DEBUG
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_PREPROD }}
          service_account_key: ${{ secrets.G_CREDENTIAL_PREPROD }}
          export_default_credentials: true
      - name: Assign Prestabulles
        run: |
          echo ${{ env.GCLOUD_PROJECT }} | sed 's/./& /g'
          gcloud components install beta
          gcloud beta secrets versions access latest --secret="accounts-module-config"
